CREATE TABLE public.tb_endereco (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	bairro varchar(255) NULL,
	cep varchar(255) NULL,
	complemento varchar(255) NULL,
	ddd varchar(255) NULL,
	gia varchar(255) NULL,
	ibge varchar(255) NULL,
	localidade varchar(255) NULL,
	logradouro varchar(255) NULL,
	uf varchar(255) NULL,
	CONSTRAINT tb_endereco_pkey PRIMARY KEY (id)
);