CREATE TABLE tb_usuario (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	login varchar(255) NULL,
	senha varchar(255) NULL,
	id_endereco int8 NULL,
	CONSTRAINT tb_usuario_pkey PRIMARY KEY (id),
	CONSTRAINT fkei_tb_usuario_if FOREIGN KEY (id_endereco) REFERENCES tb_endereco(id)
)